[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."sync-scores"]
  schedule = "*/5 * * * *"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "public/index.html"
